Logging is configured.
======================================================= test session starts ========================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project
configfile: pytest.ini
plugins: html-4.1.1, metadata-3.1.1
collected 8 items / 7 deselected / 1 selected

tests/api/test_api_todo_pixegami.py::test_api_put_create_task_missing_required_field Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 422 91
Creating task with missing one of required field.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 16:01:17 INFO Creating task with missing one of required field.
FAILED                                                                                                                        [100%]

============================================================= FAILURES =============================================================
_________________________________________ test_api_put_create_task_missing_required_field __________________________________________

    def test_api_put_create_task_missing_required_field():
        global task_id
        payload = {
            "user_id": "string",
            "task_id": "string",
            "is_done": False
        }
        response = HelperClass.create_task(payload)
        print(response)
        response_data = response.json()
        print(response_data)
    
        Logger.info('Creating task with missing one of required field.')
        status_code = response.status_code
        response_msg = response_data["detail"][0]["msg"]
        print(response_msg)
        print(status_code)
>       assert FrameworkConstant.INVALID_DATA_TYPE_MSG == response_msg
E       AssertionError: assert 'value could ... to a boolean' == 'field required'
E         
E         - field required
E         + value could not be parsed to a boolean

tests\api\test_api_todo_pixegami.py:85: AssertionError
------------------------------------------------------- Captured stdout call -------------------------------------------------------
<Response [422]>
{'detail': [{'loc': ['body', 'content'], 'msg': 'field required', 'type': 'value_error.missing'}]}
field required
422
-------------------------------------------------------- Captured log call ---------------------------------------------------------
2024-08-07 16:01:17 INFO Creating task with missing one of required field.
- Generated html report: file:///C:/Users/150194/OneDrive%20-%20Arrow%20Electronics%2C%20Inc/Documents/Python/pytest-project/reports/report.html -
===================================================== short test summary info ======================================================
FAILED tests/api/test_api_todo_pixegami.py::test_api_put_create_task_missing_required_field - AssertionError: assert 'value could ...
================================================= 1 failed, 7 deselected in 1.71s ==================================================
