Logging is configured.
======================================================= test session starts ========================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project
configfile: pytest.ini
plugins: allure-pytest-2.13.5, html-4.1.1, html-reporter-0.2.9, metadata-3.1.1
collected 10 items

tests/api/test_api_todo_pixegami.py::test_api_get getting response message

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-08 11:39:58 INFO getting response message
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET / HTTP/11" 200 39
PASSED                                                                                                                        [ 10%]
tests/api/test_api_todo_pixegami.py::test_api_put_create_task Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 200 187
Created new task with id: task_728fff4630c14787aa68459ac3316bb5

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-08 11:40:03 INFO Created new task with id: task_728fff4630c14787aa68459ac3316bb5
PASSED                                                                                                                        [ 20%]
tests/api/test_api_todo_pixegami.py::test_api_put_create_task_invalid_data_type Creating task with invalid data type.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-08 11:40:03 INFO Creating task with invalid data type.
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 422 111
PASSED                                                                                                                        [ 30%]
tests/api/test_api_todo_pixegami.py::test_api_put_create_task_missing_required_field Creating task with missing one of required field.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-08 11:40:04 INFO Creating task with missing one of required field.
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 422 91
PASSED                                                                                                                        [ 40%]
tests/api/test_api_todo_pixegami.py::test_api_put_create_task_invalid_creationtime SKIPPED (unconditional skip)               [ 50%]
tests/api/test_api_todo_pixegami.py::test_api_get_task_by_id Get task by task id: task_728fff4630c14787aa68459ac3316bb5

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-08 11:40:05 INFO Get task by task id: task_728fff4630c14787aa68459ac3316bb5
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET /get-task/task_728fff4630c14787aa68459ac3316bb5 HTTP/11" 200 178
PASSED                                                                                                                        [ 60%]
tests/api/test_api_todo_pixegami.py::test_api_get_task_by_user_id Get task by user id: Test User 1

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-08 11:40:07 INFO Get task by user id: Test User 1
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET /list-tasks/Test%20User%201 HTTP/11" 200 1040
PASSED                                                                                                                        [ 70%]
tests/api/test_api_todo_pixegami.py::test_api_update_task Update task with id: task_728fff4630c14787aa68459ac3316bb5

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-08 11:40:08 INFO Update task with id: task_728fff4630c14787aa68459ac3316bb5
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /update-task HTTP/11" 200 31
Get task with id: task_id 5 and validate update task
2024-08-08 11:40:09 INFO Get task with id: task_id 5 and validate update task
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET /get-task/task_id%205 HTTP/11" 200 76
PASSED                                                                                                                        [ 80%]
tests/api/test_api_todo_pixegami.py::test_api_update_task_creation_time SKIPPED (unconditional skip)                          [ 90%]
tests/api/test_api_todo_pixegami.py::test_api_del_task_by_id Delete task with id: task_728fff4630c14787aa68459ac3316bb5

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-08 11:40:10 INFO Delete task with id: task_728fff4630c14787aa68459ac3316bb5
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "DELETE /delete-task/task_728fff4630c14787aa68459ac3316bb5 HTTP/11" 200 59
Validate task is deleted or not.
2024-08-08 11:40:11 INFO Validate task is deleted or not.
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET /get-task/task_728fff4630c14787aa68459ac3316bb5 HTTP/11" 404 65
PASSED                                                                                                                        [100%]

================================================== 8 passed, 2 skipped in 14.50s ===================================================
